FROM python:3.11-slim

WORKDIR /app
COPY requirements.mcp.txt .

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        pkg-config \
        libmariadb-dev \
        && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.mcp.txt

CMD ["uvicorn", "mcp_server:app", "--host", "0.0.0.0", "--port", "8000"]
