FROM python:3.11-slim
WORKDIR /app
#COPY mcp_server.py .
COPY requirements.mcp.txt .
#COPY .env .
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        pkg-config \
        libmariadb-dev \
        && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.mcp.txt

CMD ["uvicorn", "mcp_server:app", "--host", "0.0.0.0", "--port", "8000"]
