# Dockerfile.agent
FROM python:3.11-slim

WORKDIR /app
COPY requirements.agent.txt .

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        pkg-config \
        libmariadb-dev \
        && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.agent.txt

